# Generated by Django 4.0.6 on 2022-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
