# Generated by Django 4.0.6 on 2022-07-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pathway', models.CharField(max_length=50)),
                ('path_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.program')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, null=True)),
                ('week', models.CharField(max_length=3)),
                ('slides', models.URLField(max_length=300, unique=True)),
                ('rectutorial', models.URLField(unique=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.topic')),
            ],
        ),
    ]
