# Generated by Django 4.0.6 on 2022-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
