# Generated by Django 4.0.6 on 2022-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_materials_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='show',
            field=models.BooleanField(null=True),
        ),
    ]
