# Generated by Django 4.0.6 on 2022-08-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, null=True)),
                ('week', models.CharField(max_length=3)),
                ('lesson_slide', models.URLField(max_length=300)),
                ('code_file', models.FileField(null=True, upload_to='resources/code')),
                ('show', models.BooleanField(null=True)),
                ('topics', models.CharField(max_length=50, null=True)),
                ('rectutorial', models.URLField(unique=True)),
                ('sub_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
