# Generated by Django 4.0.6 on 2022-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_material_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slides',
            field=models.FileField(upload_to='slides'),
        ),
    ]
