# Generated by Django 4.0.6 on 2022-07-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_material_slides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='topic',
        ),
    ]
