# Generated by Django 4.0.6 on 2022-08-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_material_pathway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='lesson_slide',
            new_name='slides',
        ),
    ]
