# Generated by Django 4.0.6 on 2022-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_rename_lesson_slide_material_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slides',
            field=models.CharField(max_length=300),
        ),
    ]
