# Generated by Django 4.0.6 on 2022-07-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_material_sub_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='topics',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
