# Generated by Django 4.0.6 on 2022-08-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_material_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
