# Generated by Django 4.0.6 on 2022-07-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_material_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slides',
            field=models.FileField(upload_to='resources/slides'),
        ),
    ]
