# Generated by Django 4.0.6 on 2022-07-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_user_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_sub',
            options={'verbose_name': 'Student Submission', 'verbose_name_plural': 'Student Submissions'},
        ),
    ]
