# Generated by Django 4.0.6 on 2022-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='topic',
        ),
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.ManyToManyField(to='cards.topics'),
        ),
    ]
