# Generated by Django 4.0.6 on 2022-08-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_topic_card_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='topic',
        ),
    ]
