# Generated by Django 4.0.6 on 2022-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='path_name',
            field=models.CharField(default='null', max_length=70),
            preserve_default=False,
        ),
    ]
