# Generated by Django 4.0.6 on 2022-08-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_program_path_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='pathway',
            new_name='program',
        ),
    ]
