# Generated by Django 4.0.6 on 2022-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
