# Generated by Django 4.0.6 on 2022-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_notes_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='rectutorial',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
