# Generated by Django 4.0.6 on 2022-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_material_rectutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='week',
            field=models.IntegerField(max_length=3),
        ),
    ]
