# Generated by Django 4.0.6 on 2022-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Sub', 'verbose_name_plural': 'Contact Subs'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='subbed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
