# Generated by Django 4.0.6 on 2022-08-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_notes_content'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stream',
            field=models.ForeignKey(default='Foundation', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='resources.program'),
        ),
    ]
