# Generated by Django 4.0.6 on 2022-08-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_post_timestamp_post_tags_reply_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='discussion_post', to='userprofile.profile'),
        ),
    ]
