# Generated by Django 4.0.6 on 2022-07-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
    ]
