# Generated by Django 4.0.6 on 2022-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='userprofile/static/avatars/default.jpg', null=True, upload_to='userprofile/static/avatars/'),
        ),
    ]
