# Generated by Django 4.0.6 on 2022-08-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
