# Generated by Django 4.0.6 on 2022-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_post_likes_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
