# Generated by Django 4.0.6 on 2022-08-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_profile_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stream',
        ),
    ]
