# Generated by Django 4.0.6 on 2022-07-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_number'),
        ('userprofile', '0007_alter_profile_avatar'),
    ]

    operations = [
    ]
